# Generated by Django 3.1b1 on 2020-06-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200621_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_catg',
            new_name='name',
        ),
    ]
