# Generated by Django 3.1b1 on 2020-07-05 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200621_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_pr',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='book',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
            preserve_default=False,
        ),
    ]
